language: bash
sudo: required

script: ./travis-build.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
