language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
